# Generated by Django 5.0.4 on 2024-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, unique=True, verbose_name='Название рецепта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('recipe_feature', models.TextField(verbose_name='Описание рецепта')),
                ('recipe_ingredients', models.TextField(verbose_name='Список ингредиентов')),
                ('steps_content', models.TextField(verbose_name='Пошаговая инструкция')),
                ('images_content', models.TextField(blank=True, default=None, null=True, verbose_name='Фотографии к шагам')),
                ('is_active', models.BooleanField(verbose_name='Активность')),
            ],
        ),
    ]
