# Generated by Django 5.0.4 on 2024-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.TextField(verbose_name='Ингредиент')),
            ],
        ),
        migrations.CreateModel(
            name='StepImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='step_images/kuritsa-na-butylke/', verbose_name='Фотография к шагу')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField(verbose_name='Шаг приготовления')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, unique=True, verbose_name='Название рецепта')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('recipe_feature', models.TextField(verbose_name='Описание рецепта')),
                ('is_active', models.BooleanField(verbose_name='Активность')),
                ('ingredient', models.ManyToManyField(related_name='ingredients', to='recipes.ingredients', verbose_name='Ингредиенты')),
                ('image', models.ManyToManyField(related_name='images', to='recipes.stepimages', verbose_name='Картинки к шагам')),
                ('step', models.ManyToManyField(related_name='steps', to='recipes.steps', verbose_name='Шаги приготовления')),
            ],
        ),
    ]
