# Generated by Django 5.0.4 on 2024-05-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepimages',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='step_images/', verbose_name='Фотография к шагу'),
        ),
    ]
