# Generated by Django 5.0.4 on 2024-05-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='recipe_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название рецепта'),
        ),
    ]
