# Generated by Django 5.1.3 on 2024-11-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=None, verbose_name='Добавлено'),
        ),
    ]
