# Generated by Django 5.1.3 on 2024-11-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_options_alter_step_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='url_parameter',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Параметр url'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Тэги поиска'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
    ]
